### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by asimumba**

### CODE REVIEW

**Comment by sellorm** [comment]
Hi @asimumba 

Thanks for the pull request!

For some reason though, your blog appears to just be a blank page and the 'zedr' blog results in a 'Page Not Found' message.

Could you let me know what's going on with those please?

Cheers,
Mark

**Comment by asimumba** [comment]
Hi, having a slight error with the blogs. Working on it now. They should be online soon. 
Cheers

**Comment by sellorm** [comment]
Let me know when they're available and I'll merge then.

Cheers,
Mark

On 13 Oct 2017 13:34, "Aaron Simumba" <notifications@github.com> wrote:

Hi, having a slight error with the blogs. Working on it now. They should be
online soon.
Cheers

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sellorm/awesome-blogdown/pull/9#issuecomment-336440065>,
or mute the thread

**Comment by asimumba** [comment]
@sellorm I have rectified all the errors and now the blogs are back online. You can verify and merge.

**Comment by sellorm** [comment]
Hi Aaron,

I've added the asimumba blog (which is great by the way!) to both the README.md here and the awesome-blogdown.com site (I haven't got round to publishing proper instructions on that just yet).

I have not added the zedr blog yet though, as it appears to be a direct copy of the asimumba one. Is that intentional? I'd rather keep Awesome Blogdown full of the freshest/best content possible, and I'm reluctant to add a duplicate blog.

It's fine if that's going to change over time, I'd just prefer to wait until it's ready before I publish that one.

So what's happening with the zedr blog?

Many thanks,
Mark

**Comment by asimumba** [comment]
Hi Sellorm, 
Thank you for the kind words. I appreciate the feedback.

On the zedr blog, this is meant to be a student led blog from the University of Zambia. I posted the copy of my personal blog just was a set-up. Over time it will completely transform with independent work from my personal blog. Since I am still finalising the grounp of members, I thought to take ownership in the interim.

Thanks once more.

**Comment by sellorm** [comment]
Thanks for the update - I've added it now.

**Comment by sellorm** [comment]
Hi Aaron,

There seems to be an issue with https://asimumba.rbind.io - is this something you intend to fix, or should I remove it from the list?

Cheers,
Mark

**Comment by asimumba** [comment]
@sellorm So the issue seemed to occur with the subdomain throwing up certificates errors when you try to access the site. This was reported and resolved, see [here](https://github.com/rbind/support/issues/260). Thank you

**Comment by sellorm** [comment]
I still get the error below.
error

**Comment by asimumba** [comment]
@sellorm Fun part is I'm able to access the site from my end. 
screenshot. I will take a closer look, this has been a reoccuring error the past 2 weeks.

**Comment by sellorm** [comment]
If it helps, it showed up in my monitoring on the 10th, but it was fine on
the 8th. (I don't check every day.)

On 13 Aug 2018 12:06, "Aaron Simumba" <notifications@github.com> wrote:

@sellorm <https://github.com/sellorm> So the issue seemed to occur with the
subdomain throwing up certificates errors when you try to access the site.
This was reported and resolved, see here
<https://github.com/rbind/support/issues/260>. Thank you

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sellorm/awesome-blogdown/pull/9#issuecomment-412483239>,
or mute the thread

**Comment by sellorm** [comment]
The monitoring today showed it as all clear so I'll close this again

**Pull request closed without merging**
