### PR TITLE
Update sites.json

### PR DESCRIPTION
**Pull request by statnmap**
Add 3 new blogdown's blogs

### CODE REVIEW

**Comment by sellorm** [comment]
HI Sebastien,

Thanks for the pull request!

One of the sites wont load for me though - https://marionlouveaux.free.fr

Is there an issue with the site?

Thanks again,
Mark

**Comment by statnmap** [comment]
I think this is because it is not a https but a http website.

**Comment by sellorm** [comment]
Ah, OK - Could you update the pull request with the correct URL?

Many thanks,
Mark

**Comment by sellorm** [comment]
Thanks very much!

**Comment by statnmap** [comment]
Thank you for this list

**Pull request merged**
